@startuml
left to right direction
actor "Používateľ" as user
rectangle ER_Modeler {
    usecase "Spravovať existujúcu doménu" as edit_domain
    usecase "Exportovať SQL DDL príkazy" as export_sql
    usecase "Exportovať diagram do grafickej podoby" as export_svg
    usecase "Uložiť projekt" as save_project
    usecase "Načítať projekt" as load_project
}

user --> export_sql
user --> export_svg
user --> save_project
user --> load_project

@enduml